### ISSUE TITLE
CD for the API

### ISSUE THREAD

**Issue by tessmichi** [fireflies-crew/hello-api#7] opened 2021-04-28 17:32 UTC
deploy the web app to the VM via script not visual studio UI

**Comment by tessmichi** [comment] 2021-04-28 17:33
I believe this is being covered by Tanner and Neeraj under the CircleCI umbrella but adding anyway as it came up in the VM portion of standup

**Comment by wbreza** [comment] 2021-04-28 18:15
Duplicate of #11

**Closed** 2021-04-28 18:14 UTC
